### ISSUE TITLE
local run of deploy.ps1 fails due to incorrect path assumption

### ISSUE THREAD

**Issue by SteveALee** [adrianhall/azure-mobile-apps-html-quickstart#2]
I run

``` cmd
powershell .\deploy.ps1
```

which installs kudosync but then fails to run it as it's not in the expected place

``` cmd
Installing Kudu Sync
C:\Program Files\nodejs\kudusync -> C:\Program Files\nodejs\node_modules\kudusync\bin\kudusync
C:\Program Files\nodejs
`-- kudusync@0.2.3
  +-- commander@2.6.0
  +-- minimatch@2.0.1
  | `-- brace-expansion@1.1.5
  |   +-- balanced-match@0.4.1
  |   `-- concat-map@0.0.1
  `-- q@1.1.2

Handling node.js deployment.
& : The term 'C:\Users\steve\AppData\Roaming\npm\kuduSync.cmd' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\projects\azure\azure-mobile-apps-html-quickstart\deploy.ps1:106 char:5
+   & $KUDU_SYNC_CMD -v 50 -f "$DEPLOYMENT_SOURCE" -t "$DEPLOYMENT_TARG ...
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\steve\...pm\kuduSync.cmd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

An error has occurred during web site deployment.
Kudu Sync failed

C:\projects\azure\azure-mobile-apps-html-quickstart>npm list kudusync
azure-mobile-apps-html-quickstart@0.1.0 C:\projects\azure\azure-mobile-apps-html-quickstart
`-- (empty)

npm ERR! code 1
```
As shown in the output kudusync is installed in 'Program Files' not under 'Roaming'

I'm using node 5.10.1 with npm 3.8.3. I'm also using nvm-windows but that should make no difference.

**Comment by SteveALee** [comment]
OK i'm using 64 bit node - but again that should make no difference

The problem is [here](https://github.com/azure-appservice-samples/ContosoMoments/blob/master/deploy.cmd#L48)

It looks like you should use use the output of ```npm root -g```.

**Comment by SteveALee** [comment]
A final comment is that if you want to use the package script rather than platform specific exe as I suggested then this might be useful

https://github.com/npm/npm/issues/6674

**Comment by adrianhall** [comment]
deploy.ps1 is not meant for local development - it's meant for deploying to the cloud.  It should only be run as part of the Azure Cloud and specifically Azure App Service - not on a local box.

**Comment by SteveALee** [comment]
Well [this comment line](https://github.com/azure-appservice-samples/ContosoMoments/blob/master/deploy.cmd#L47) and [these kudo docs](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script) (that you pointed me to) indicate that local running is intended for these scripts in general - even if not in your specific case. 

Perhaps local running is out of date now? To be honest the main use for local testing is when travelling and having no connectivity. However local and offline dev/test is a nice to have.

Maybe referencing kudosync on the path would be better than absolute - especially as the deployment env is well controlled. But that is a mute point given your statement on local running
